sylius_resource:
    resources:
        bitbag_sylius_przelewy24_plugin.card:
            driver: doctrine/orm
            classes:
                model: BitBag\SyliusPrzelewy24Plugin\Subscription\Entity\Card
                interface: BitBag\SyliusPrzelewy24Plugin\Subscription\Entity\CardInterface
                repository: BitBag\SyliusPrzelewy24Plugin\Subscription\Repository\CardRepository
