sylius_resource:
    resources:
        bitbag_sylius_przelewy24_plugin.recurring_order:
            driver: doctrine/orm
            classes:
                model: BitBag\SyliusPrzelewy24Plugin\Subscription\Entity\RecurringOrder
                interface: BitBag\SyliusPrzelewy24Plugin\Subscription\Entity\RecurringOrderInterface
