services:
    bitbag_sylius_przelewy24_plugin.applicator.przelewy24_subscription_based_router_context:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Applicator\Przelewy24SubscriptionBasedRouterContextApplicator
        arguments:
            - '@router'

    bitbag_sylius_przelewy24_plugin.applicator.payment_failed_state:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Applicator\PaymentFailedStateApplicator
        arguments:
            - '@sm.factory'
            - '@sylius.repository.payment'
