services:
    bitbag.sylius_przelewy24_plugin.assigner.payment_payload.empty_payload:
        class: BitBag\SyliusPrzelewy24Plugin\Shared\Assigner\TransactionPayloadEmptyPayloadAssigner
        arguments:
            - 'BitBag\SyliusPrzelewy24Plugin\Shared\Payload\PaymentPayload'

    bitbag.sylius_przelewy24_plugin.assigner.add_card_payload.empty_payload:
        class: BitBag\SyliusPrzelewy24Plugin\Shared\Assigner\TransactionPayloadEmptyPayloadAssigner
        arguments:
            - 'BitBag\SyliusPrzelewy24Plugin\Subscription\Payload\AddCardPayload'

    bitbag.sylius_przelewy24_plugin.assigner.payment_payload.after_url:
        class: BitBag\SyliusPrzelewy24Plugin\Shared\Assigner\TransactionPayloadAfterUrlAssigner
        arguments:
            - '@bitbag.sylius_przelewy24_plugin.resolver.payment.after_url'

    bitbag.sylius_przelewy24_plugin.assigner.add_card_payload.after_url:
        class: BitBag\SyliusPrzelewy24Plugin\Shared\Assigner\TransactionPayloadAfterUrlAssigner
        arguments:
            - '@bitbag.sylius_przelewy24_plugin.resolver.add_card.after_url'

    bitbag.sylius_przelewy24_plugin.assigner.payment_payload.notify_url:
        class: BitBag\SyliusPrzelewy24Plugin\Shared\Assigner\TransactionPayloadNotifyUrlAssigner
        arguments:
            - '@bitbag.sylius_przelewy24_plugin.resolver.payment.notify_url'

    bitbag.sylius_przelewy24_plugin.assigner.add_card_payload.notify_url:
        class: BitBag\SyliusPrzelewy24Plugin\Shared\Assigner\TransactionPayloadNotifyUrlAssigner
        arguments:
            - '@bitbag.sylius_przelewy24_plugin.resolver.add_card.notify_url'

    bitbag.sylius_przelewy24_plugin.assigner.transaction_payload.session_id:
        class: BitBag\SyliusPrzelewy24Plugin\Shared\Assigner\TransactionPayloadSessionIdAssigner
        arguments:
            - '@sylius.random_generator'

    bitbag.sylius_przelewy24_plugin.assigner.transaction_payload.transaction_token:
        class: BitBag\SyliusPrzelewy24Plugin\Shared\Assigner\TransactionPayloadTokenAssigner

    bitbag.sylius_przelewy24_plugin.assigner.payment_payload.recurring:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Assigner\PaymentPayloadRecurringAssigner
        arguments:
            - '@bitbag.sylius_przelewy24_plugin.checker.is_payment_order_recurring'

    bitbag.sylius_przelewy24_plugin.assigner.payment_payload.pay_with_existing_card:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Assigner\PaymentPayloadPayWithExistingCardAssigner
        arguments:
            - '@bitbag.sylius_przelewy24_plugin.checker.is_paying_with_existing_card'

    bitbag.sylius_przelewy24_plugin.assigner.payment_payload.initializing_subscription:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Assigner\PaymentPayloadInitializingSubscriptionAssigner
        arguments:
            - '@bitbag.sylius_przelewy24_plugin.checker.is_payment_initializing_subscription'

    bitbag.sylius_przelewy24_plugin.assigner.payment_payload.card_ref_id:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Assigner\PaymentPayloadCardRefIdAssigner
        arguments:
            - '@bitbag.sylius_przelewy24_plugin.resolver.card_ref_id'

    bitbag.sylius_przelewy24_plugin.assigner.composite_payment_payload.one_time_transaction_session:
        class: BitBag\SyliusPrzelewy24Plugin\Shared\Assigner\CompositeTransactionPayloadSessionAssigner
        calls:
            - [addAssigner, ['@bitbag.sylius_przelewy24_plugin.assigner.payment_payload.empty_payload', '400']]
            - [addAssigner, ['@bitbag.sylius_przelewy24_plugin.assigner.transaction_payload.session_id', '300']]
            - [addAssigner, ['@bitbag.sylius_przelewy24_plugin.assigner.payment_payload.after_url', '200']]
            - [addAssigner, ['@bitbag.sylius_przelewy24_plugin.assigner.payment_payload.notify_url', '100']]

    bitbag.sylius_przelewy24_plugin.assigner.composite_payment_payload.subscription_transaction_session:
        class: BitBag\SyliusPrzelewy24Plugin\Shared\Assigner\CompositeTransactionPayloadSessionAssigner
        calls:
            - [addAssigner, ['@bitbag.sylius_przelewy24_plugin.assigner.payment_payload.empty_payload', '700']]
            - [addAssigner, ['@bitbag.sylius_przelewy24_plugin.assigner.transaction_payload.session_id', '600']]
            - [addAssigner, ['@bitbag.sylius_przelewy24_plugin.assigner.payment_payload.after_url', '500']]
            - [addAssigner, ['@bitbag.sylius_przelewy24_plugin.assigner.payment_payload.notify_url', '400']]
            - [addAssigner, ['@bitbag.sylius_przelewy24_plugin.assigner.payment_payload.card_ref_id', '300']]
            - [addAssigner, ['@bitbag.sylius_przelewy24_plugin.assigner.payment_payload.recurring', '300']]
            - [addAssigner, ['@bitbag.sylius_przelewy24_plugin.assigner.payment_payload.pay_with_existing_card', '200']]
            - [addAssigner, ['@bitbag.sylius_przelewy24_plugin.assigner.payment_payload.initializing_subscription', '100']]

    bitbag.sylius_przelewy24_plugin.assigner.composite_add_card_payload.add_card_transaction_session:
        class: BitBag\SyliusPrzelewy24Plugin\Shared\Assigner\CompositeTransactionPayloadSessionAssigner
        calls:
            - [addAssigner, ['@bitbag.sylius_przelewy24_plugin.assigner.add_card_payload.empty_payload', '200']]
            - [addAssigner, ['@bitbag.sylius_przelewy24_plugin.assigner.transaction_payload.session_id', '100']]

    bitbag.sylius_przelewy24_plugin.assigner.composite_add_card_payload.add_card_transaction_urls:
        class: BitBag\SyliusPrzelewy24Plugin\Shared\Assigner\CompositeTransactionPayloadSessionAssigner
        calls:
            - [addAssigner, ['@bitbag.sylius_przelewy24_plugin.assigner.add_card_payload.after_url', '200']]
            - [addAssigner, ['@bitbag.sylius_przelewy24_plugin.assigner.add_card_payload.notify_url', '100']]

    bitbag.sylius_przelewy24_plugin.assigner.transaction_response.gateway_url:
        class: BitBag\SyliusPrzelewy24Plugin\Shared\Assigner\TransactionResponseGatewayUrlAssigner

    bitbag.sylius_przelewy24_plugin.assigner.add_card_payload.notify_request_hash:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Assigner\AddCardPayloadNotifyRequestHashAssigner
