services:
    bitbag.sylius_przelewy24_plugin.checker.has_order_recurring_products:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Checker\HasOrderRecurringProductsChecker

    bitbag.sylius_przelewy24_plugin.checker.is_payment_order_recurring:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Checker\IsPaymentOrderRecurringChecker

    bitbag.sylius_przelewy24_plugin.checker.is_paying_with_existing_card:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Checker\IsPayingWithExistingCardChecker

    bitbag.sylius_przelewy24_plugin.checker.is_payment_initializing_subscription:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Checker\IsPaymentInitializingSubscriptionChecker

    bitbag.sylius_przelewy24_plugin.checker.has_order_recurring_items_checker:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Checker\HasOrderRecurringProductsChecker

    bitbag.sylius_przelewy24_plugin.checker.composite_przelewy24_one_time_transaction_notification_validity:
        class: BitBag\SyliusPrzelewy24Plugin\Shared\Checker\CompositeTransactionNotificationValidityChecker
        arguments:
            - '@bitbag.sylius_przelewy24_plugin.synchronizer.composite_przelewy24_one_time_transaction'
        calls:
            - ['addChecker', [ '@bitbag.sylius_przelewy24_plugin.przelewy24.checker.transaction_notification_session_id_validity', '200']]
            - ['addChecker', [ '@bitbag.sylius_przelewy24_plugin.przelewy24.checker.transaction_notification_sign_validity', '100']]

    bitbag.sylius_przelewy24_plugin.checker.composite_przelewy24_subscription_transaction_notification_validity:
        class: BitBag\SyliusPrzelewy24Plugin\Shared\Checker\CompositeTransactionNotificationValidityChecker
        arguments:
            - '@bitbag.sylius_przelewy24_plugin.synchronizer.composite_przelewy24_subscription_transaction'
        calls:
            - ['addChecker', ['@bitbag.sylius_przelewy24_plugin.przelewy24.checker.transaction_notification_session_id_validity', '200']]
            - ['addChecker', ['@bitbag.sylius_przelewy24_plugin.przelewy24.checker.transaction_notification_sign_validity', '100']]

    bitbag.sylius_przelewy24_plugin.checker.composite_add_card_transaction_notification_validity:
        class: BitBag\SyliusPrzelewy24Plugin\Shared\Checker\CompositeTransactionNotificationValidityChecker
        arguments:
            - '@bitbag.sylius_przelewy24_plugin.synchronizer.composite_add_card_transaction'
        calls:
            - ['addChecker', ['@bitbag.sylius_przelewy24_plugin.przelewy24.checker.transaction_notification_session_id_validity', '200']]
            - ['addChecker', ['@bitbag.sylius_przelewy24_plugin.przelewy24.checker.transaction_notification_sign_validity', '100']]
