services:
    bitbag_sylius_przelewy24_plugin.checker.is_przelewy24_subscription_payment_failed:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Checker\IsPrzelewy24SubscriptionPaymentFailedChecker
        arguments:
            - '@payum'
