services:
    bitbag.sylius_przelewy24_plugin.cli.process_subscriptions:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Cli\ProcessSubscriptions
        arguments:
            - '@bitbag.sylius_przelewy24_plugin.subscription_processing.active_subscriptions_processor'
        tags:
            - name: console.command
