services:
    bitbag.sylius_przelewy24_plugin.cloner.adjustment:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Cloner\AdjustmentCloner
        arguments:
            - '@sylius.factory.adjustment'

    bitbag.sylius_przelewy24_plugin.cloner.order_item:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Cloner\OrderItemCloner
        arguments:
            - '@sylius.factory.order_item'
            - '@sylius.factory.order_item_unit'

    bitbag.sylius_przelewy24_plugin.cloner.order:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Cloner\OrderCloner
        arguments:
            - '@sylius.factory.order'
            - '@sylius.number_assigner.order_number'
            - '@clock'
            - '@sylius.random_generator'
            - '@bitbag.sylius_przelewy24_plugin.cloner.order_item'
            - '@bitbag.sylius_przelewy24_plugin.cloner.adjustment'
            - '@bitbag.sylius_przelewy24_plugin.cloner.shipment'

    bitbag.sylius_przelewy24_plugin.cloner.shipment:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Cloner\ShipmentCloner
        arguments:
            - '@sylius.factory.shipment'
            - '@clock'
