services:
    bitbag_sylius_przelewy24_plugin.command_handler.mark_order_recurring:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\CommandHandler\MarkOrderRecurringHandler
        arguments:
            - '@bitbag_sylius_przelewy24_plugin.repository.przelewy24_order'
        tags:
            - { name: messenger.message_handler, handles: BitBag\SyliusPrzelewy24Plugin\Subscription\Command\MarkOrderRecurringCommand }

    bitbag_sylius_przelewy24_plugin.command_handler.mark_order_not_recurring:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\CommandHandler\MarkOrderNotRecurringHandler
        arguments:
            - '@bitbag_sylius_przelewy24_plugin.repository.przelewy24_order'
        tags:
            - { name: messenger.message_handler, handles: BitBag\SyliusPrzelewy24Plugin\Subscription\Command\MarkOrderNotRecurringCommand }

    bitbag_sylius_przelewy24_plugin.command_handler.register_new_subscription:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\CommandHandler\RegisterNewSubscriptionHandler
        arguments:
            - '@sylius.repository.order'
            - '@bitbag_sylius_przelewy24_plugin.custom_factory.przelewy24_subscription'
            - '@bitbag_sylius_przelewy24_plugin.repository.przelewy24_subscription'
        tags:
            - { name: messenger.message_handler, handles: BitBag\SyliusPrzelewy24Plugin\Subscription\Command\RegisterNewSubscriptionCommand }

    bitbag_sylius_przelewy24_plugin.command_handler.save_przelewy24_credit_card_if_not_exists:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\CommandHandler\SavePrzelewy24CreditCardIfNotExistsHandler
        arguments:
            - '@bitbag_sylius_przelewy24_plugin.repository.przelewy24_credit_card'
            - '@bitbag_sylius_przelewy24_plugin.repository.przelewy24_customer'
            - '@bitbag_sylius_przelewy24_plugin.custom_factory.przelewy24_credit_card'
        tags:
            - { name: messenger.message_handler, handles: BitBag\SyliusPrzelewy24Plugin\Subscription\Command\SavePrzelewy24CreditCardIfNotExistsCommand }
