services:
    bitbag.sylius_przelewy24_plugin.counter.subscription_interval_failure:
        public: true
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Counter\SubscriptionIntervalFailureCounter
        arguments:
            - '@bitbag_sylius_przelewy24_plugin.repository.subscription_interval'
