services:
    bitbag.sylius_przelewy24_plugin.custom_factory.card:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Factory\CardFactory
        decorates: bitbag_sylius_przelewy24_plugin.factory.card
        arguments:
            - '@bitbag.sylius_przelewy24_plugin.custom_factory.card.inner'
            - '@sylius.random_generator'

    bitbag.sylius_przelewy24_plugin.custom_factory.subscription_configuration:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Factory\SubscriptionConfigurationFactory
        decorates: bitbag_sylius_przelewy24_plugin.factory.subscription_configuration
        arguments:
            - '@bitbag.sylius_przelewy24_plugin.custom_factory.subscription_configuration.inner'
            - '@router'
            - '@bitbag_sylius_przelewy24_plugin.repository.card'
            - '@bitbag.sylius_przelewy24_plugin.provider.payment_payload'

    bitbag.sylius_przelewy24_plugin.custom_factory.subscription:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Factory\SubscriptionFactory
        decorates: bitbag_sylius_przelewy24_plugin.factory.subscription
        arguments:
            - '@bitbag.sylius_przelewy24_plugin.custom_factory.subscription.inner'
            - '@clock'
            - '@bitbag.sylius_przelewy24_plugin.custom_factory.subscription_configuration'
            - '@bitbag.sylius_przelewy24_plugin.generator.subscription_schedule'

    bitbag.sylius_przelewy24_plugin.custom_factory.subscription_schedule:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Factory\SubscriptionScheduleFactory
        decorates: bitbag_sylius_przelewy24_plugin.factory.subscription_schedule
        arguments:
            - '@bitbag.sylius_przelewy24_plugin.custom_factory.subscription_schedule.inner'

    bitbag.sylius_przelewy24_plugin.custom_factory.subscription_interval:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Factory\SubscriptionIntervalFactory
        decorates: bitbag_sylius_przelewy24_plugin.factory.subscription_interval
        arguments:
            - '@bitbag.sylius_przelewy24_plugin.custom_factory.subscription_interval.inner'


