services:
    bitbag_sylius_przelewy24_plugin.form.type.przelewy24_one_time_gateway_configuration:
        class: BitBag\SyliusPrzelewy24Plugin\OneTime\Form\Type\Przelewy24OneTimeGatewayConfigurationType
        tags:
            - { name: sylius.gateway_configuration_type, type: przelewy24_one_time, label: bitbag_sylius_przelewy24_plugin.ui.one_time_gateway_label }
            - { name: form.type }

    bitbag_sylius_przelewy24_plugin.form.type.przelewy24_subscription_gateway_configuration:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Form\Type\Przelewy24SubscriptionGatewayConfigurationType
        tags:
            - { name: sylius.gateway_configuration_type, type: przelewy24_subscription, label: bitbag_sylius_przelewy24_plugin.ui.subscription_gateway_label }
            - { name: form.type }

    bitbag_sylius_przelewy24_plugin.form.extension.recurring_product_variant:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Form\Extension\RecurringProductVariantExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\ProductBundle\Form\Type\ProductVariantType }
