services:
    bitbag_sylius_przelewy24_plugin.gateway_factory.przelewy24:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments:
            -  BitBag\SyliusPrzelewy24Plugin\Przelewy24GatewayFactory
        tags:
            - { name: payum.gateway_factory_builder, factory: przelewy24 }
