services:
    bitbag_sylius_przelewy24_plugin.gateway_factory.przelewy24_one_time:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments:
            -  BitBag\SyliusPrzelewy24Plugin\OneTime\Przelewy24OneTimeGatewayFactory
        tags:
            - { name: payum.gateway_factory_builder, factory: przelewy24_one_time }

    bitbag_sylius_przelewy24_plugin_gateway_factory.przelewy24_subscription:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments:
            -  BitBag\SyliusPrzelewy24Plugin\Subscription\Przelewy24SubscriptionGatewayFactory
        tags:
            - { name: payum.gateway_factory_builder, factory: przelewy24_subscription }
