services:
    bitbag.sylius_przelewy24_plugin.generator.subscription_schedule:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Generator\SubscriptionScheduleGenerator
        arguments:
            - '@bitbag.sylius_przelewy24_plugin.custom_factory.subscription_schedule'
            - '@bitbag.sylius_przelewy24_plugin.custom_factory.subscription_interval'
