services:
    bitbag_sylius_przelewy24_plugin.event_listener.any_product_pre_add_to_recurring_order:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\EventListener\AnyProductPreAddToRecurringOrderListener
        arguments:
            - '@sylius.context.cart.composite'
        tags:
            - { name: kernel.event_listener, event: sylius.order_item.pre_add, method: preventAddingAnyProductToRecurringOrder }

    bitbag_sylius_przelewy24_plugin.event_listener.recurring_order_pre_update:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\EventListener\RecurringOrderPreUpdateListener
        tags:
            - { name: kernel.event_listener, event: sylius.order.pre_update, method: preventOrderUpdateIfOrderIsRecurringAndChangedTotalQuantity }

    bitbag_sylius_przelewy24_plugin.event_listener.recurring_product_post_add_to_not_recurring_order:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\EventListener\RecurringProductPostAddToNotRecurringOrderListener
        arguments:
            - '@messenger.default_bus'
            - '@sylius.context.cart.composite'
        tags:
            - { name: kernel.event_listener, event: sylius.order_item.post_add, method: markOrderAsRecurringIfAddedProductIsRecurring }

    bitbag_sylius_przelewy24_plugin.event_listener.recurring_product_post_remove_from_recurring_order:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\EventListener\RecurringProductPostRemoveFromRecurringOrderListener
        arguments:
            - '@messenger.default_bus'
            - '@sylius.context.cart.composite'
        tags:
            - { name: kernel.event_listener, event: sylius.order_item.post_remove, method: markOrderAsNotRecurringIfRemovedProductIsRecurring }

    bitbag_sylius_przelewy24_plugin.event_listener.recurring_product_pre_add_to_not_recurring_order:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\EventListener\RecurringProductPreAddToNotRecurringOrderListener
        arguments:
            - '@sylius.context.cart.composite'
        tags:
            - { name: kernel.event_listener, event: sylius.order_item.pre_add, method: preventAddingRecurringProductToNotRecurringOrderIfOrderHasAnyProducts, priority: 200 }
            - { name: kernel.event_listener, event: sylius.order_item.pre_add, method: preventAddingMoreThanOneRecurringProductToNotRecurringOrder, priority: 100 }
