services:
    bitbag.sylius_przelewy24_plugin.command_provider.payment.przelewy24_one_time:
        class: Sylius\Bundle\PaymentBundle\CommandProvider\ActionsCommandProvider
        arguments:
            - !tagged_locator
                tag: bitbag.sylius_przelewy24_plugin.command_provider.payment.przelewy24_one_time
                index_by: 'action'
        tags:
            - name: sylius.payment_request.command_provider
              gateway-factory: 'przelewy24_one_time'

    bitbag.sylius_przelewy24_plugin.command_provider.payment.przelewy24_one_time.capture:
        class: BitBag\SyliusPrzelewy24Plugin\OneTime\CommandProvider\Payment\CapturePaymentRequestCommandProvider
        tags:
            - name: bitbag.sylius_przelewy24_plugin.command_provider.payment.przelewy24_one_time
              action: !php/const Sylius\Component\Payment\Model\PaymentRequestInterface::ACTION_CAPTURE

    bitbag.sylius_przelewy24_plugin.command_provider.payment.przelewy24_one_time.notify:
        class: BitBag\SyliusPrzelewy24Plugin\OneTime\CommandProvider\Payment\NotifyPaymentRequestCommandProvider
        tags:
            - name: bitbag.sylius_przelewy24_plugin.command_provider.payment.przelewy24_one_time
              action: !php/const Sylius\Component\Payment\Model\PaymentRequestInterface::ACTION_NOTIFY

    bitbag.sylius_przelewy24_plugin.command_provider.payment.przelewy24_one_time.status:
        class: BitBag\SyliusPrzelewy24Plugin\OneTime\CommandProvider\Payment\StatusPaymentRequestCommandProvider
        tags:
            - name: bitbag.sylius_przelewy24_plugin.command_provider.payment.przelewy24_one_time
              action: !php/const Sylius\Component\Payment\Model\PaymentRequestInterface::ACTION_STATUS

    bitbag.sylius_przelewy24_plugin.command_provider.payment.przelewy24_one_time.sync:
        class: BitBag\SyliusPrzelewy24Plugin\OneTime\CommandProvider\Payment\SyncPaymentRequestCommandProvider
        tags:
            - name: bitbag.sylius_przelewy24_plugin.command_provider.payment.przelewy24_one_time
              action: !php/const Sylius\Component\Payment\Model\PaymentRequestInterface::ACTION_SYNC

    bitbag.sylius_przelewy24_plugin.command_provider.payment.przelewy24_subscription:
        class: Sylius\Bundle\PaymentBundle\CommandProvider\ActionsCommandProvider
        arguments:
            - !tagged_locator
                tag: bitbag.sylius_przelewy24_plugin.command_provider.payment.przelewy24_subscription
                index_by: 'action'
        tags:
            - name: sylius.payment_request.command_provider
              gateway-factory: 'przelewy24_subscription'

    bitbag.sylius_przelewy24_plugin.command_provider.payment.przelewy24_subscription.capture:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\CommandProvider\Payment\CapturePaymentRequestCommandProvider
        tags:
            - name: bitbag.sylius_przelewy24_plugin.command_provider.payment.przelewy24_subscription
              action: !php/const Sylius\Component\Payment\Model\PaymentRequestInterface::ACTION_CAPTURE

    bitbag.sylius_przelewy24_plugin.command_provider.payment.przelewy24_subscription.notify:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\CommandProvider\Payment\NotifyPaymentRequestCommandProvider
        tags:
            - name: bitbag.sylius_przelewy24_plugin.command_provider.payment.przelewy24_subscription
              action: !php/const Sylius\Component\Payment\Model\PaymentRequestInterface::ACTION_NOTIFY

    bitbag.sylius_przelewy24_plugin.command_provider.payment.przelewy24_subscription.status:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\CommandProvider\Payment\StatusPaymentRequestCommandProvider
        tags:
            - name: bitbag.sylius_przelewy24_plugin.command_provider.payment.przelewy24_subscription
              action: !php/const Sylius\Component\Payment\Model\PaymentRequestInterface::ACTION_STATUS

    bitbag.sylius_przelewy24_plugin.command_provider.payment.przelewy24_subscription.sync:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\CommandProvider\Payment\SyncPaymentRequestCommandProvider
        tags:
            - name: bitbag.sylius_przelewy24_plugin.command_provider.payment.przelewy24_subscription
              action: !php/const Sylius\Component\Payment\Model\PaymentRequestInterface::ACTION_SYNC
