services:
    bitbag.sylius_przelewy24_plugin.processor.payment_request:
        class: BitBag\SyliusPrzelewy24Plugin\Shared\Processor\PaymentRequestProcessor
        arguments:
            - '@sylius_abstraction.state_machine'
            - '@logger'

    bitbag.sylius_przelewy24_plugin.processor.przelewy24_one_time_payment_notification:
        class: BitBag\SyliusPrzelewy24Plugin\Shared\Processor\TransactionNotificationProcessor
        arguments:
            - '@bitbag.sylius_przelewy24_plugin.checker.composite_przelewy24_one_time_transaction_notification_validity'
            - '@bitbag.sylius_przelewy24_plugin.przelewy24.verifier.transaction'
            - '@bitbag.sylius_przelewy24_plugin.przelewy24.state_resolver.payment'

    bitbag.sylius_przelewy24_plugin.processor.przelewy24_subscription_payment_notification:
        class: BitBag\SyliusPrzelewy24Plugin\Shared\Processor\TransactionNotificationProcessor
        arguments:
            - '@bitbag.sylius_przelewy24_plugin.checker.composite_przelewy24_subscription_transaction_notification_validity'
            - '@bitbag.sylius_przelewy24_plugin.przelewy24.verifier.transaction'
            - '@bitbag.sylius_przelewy24_plugin.przelewy24.state_resolver.payment'
