services:
    bitbag.sylius_przelewy24_plugin.provider.payment_payload:
        class: BitBag\SyliusPrzelewy24Plugin\Shared\Provider\PaymentPayloadProvider

    bitbag.sylius_przelewy24_plugin.provider.przelewy24_gateway_notify_payment:
        class: BitBag\SyliusPrzelewy24Plugin\Shared\Provider\Przelewy24GatewayNotifyPaymentProvider
        arguments:
            - '@sylius.repository.payment_request'
        tags:
            - name: sylius.payment_request.payment_notify_provider
