services:
    bitbag.sylius_przelewy24_plugin.resolver.payment_methods.default:
        decorates: sylius.resolver.payment_methods.default
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Resolver\PaymentMethod\PaymentMethodsResolver
        arguments:
            - '@bitbag.sylius_przelewy24_plugin.resolver.payment_methods.default.inner'

    bitbag.sylius_przelewy24_plugin.resolver.payment_methods.channel_based:
        decorates: sylius.resolver.payment_methods.channel_based
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Resolver\PaymentMethod\PaymentMethodsResolver
        arguments:
            - '@bitbag.sylius_przelewy24_plugin.resolver.payment_methods.channel_based.inner'

    bitbag.sylius_przelewy24_plugin.resolver.payment_method.default:
        decorates: sylius.resolver.payment_method.default
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Resolver\PaymentMethod\DefaultPaymentMethodResolver
        arguments:
            - '@bitbag.sylius_przelewy24_plugin.resolver.payment_method.default.inner'
            - '@bitbag.sylius_przelewy24_plugin.resolver.subscription_payment_method'

    bitbag.sylius_przelewy24_plugin.resolver.subscription_payment_method:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Resolver\PaymentMethod\SubscriptionPaymentMethodResolver
        arguments:
            - '@sylius.repository.payment_method'

    bitbag.sylius_przelewy24_plugin.resolver.payment.after_url:
        class: BitBag\SyliusPrzelewy24Plugin\Shared\Resolver\PaymentAfterUrlResolver
        arguments:
            - '@bitbag.sylius_przelewy24_plugin.provider.payment_http_request'
            - '@router'

    bitbag.sylius_przelewy24_plugin.resolver.payment.notify_url:
        class: BitBag\SyliusPrzelewy24Plugin\Shared\Resolver\PaymentNotifyUrlResolver
        arguments:
            - '@router'

    bitbag.sylius_przelewy24_plugin.resolver.card_ref_id:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Resolver\CardRefIdResolver
        arguments:
            - '@bitbag_sylius_przelewy24_plugin.repository.card'
