services:
    bitbag_sylius_przelewy24_plugin.state_processor.sylius_payment:
        public: true
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\StateProcessor\SyliusPaymentStateProcessor
        arguments:
            - '@bitbag_sylius_przelewy24_plugin.counter.przelewy24_subscription_schedule_interval_failure_counter'
            - '@bitbag_sylius_przelewy24_plugin.state_resolver.przelewy24_subscription_schedule_interval'
            - '@bitbag_sylius_przelewy24_plugin.command_dispatcher.register_new_subscription'
            - '@bitbag_sylius_przelewy24_plugin.command_dispatcher.save_przelewy24_credit_card_if_not_exists'
