services:
    bitbag.sylius_przelewy24_plugin.voter.card:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Voter\CardVoter
        arguments:
            - '@security.helper'
        tags:
            - name: security.voter

    bitbag.sylius_przelewy24_plugin.voter.subscriber:
        class: BitBag\SyliusPrzelewy24Plugin\Subscription\Voter\SubscriberVoter
        arguments:
            - '@security.helper'
        tags:
            - name: security.voter
