sylius_resource:
    resources:
        bitbag_sylius_przelewy24_plugin.przelewy24_subscription_schedule:
            driver: doctrine/orm
            classes:
                model: BitBag\SyliusPrzelewy24Plugin\Subscription\Entity\Przelewy24SubscriptionSchedule
                interface: BitBag\SyliusPrzelewy24Plugin\Subscription\Entity\Przelewy24SubscriptionScheduleInterface
