sylius_resource:
    resources:
        bitbag_sylius_przelewy24_plugin.przelewy24_subscription_schedule_interval:
            driver: doctrine/orm
            classes:
                model: BitBag\SyliusPrzelewy24Plugin\Subscription\Entity\Przelewy24SubscriptionScheduleInterval
                interface: BitBag\SyliusPrzelewy24Plugin\Subscription\Entity\Przelewy24SubscriptionScheduleIntervalInterface
                repository: BitBag\SyliusPrzelewy24Plugin\Subscription\Repository\Przelewy24SubscriptionScheduleIntervalRepository
