winzou_state_machine:
    przelewy24_subscription:
        class: "%bitbag_sylius_przelewy24_plugin.model.przelewy24_subscription.class%"
        property_path: state
        graph: bitbag_sylius_przelewy24_plugin_przelewy24_subscription_graph
        state_machine_class: "%sylius.state_machine.class%"
        states:
            active: ~
            completed: ~
            aborted: ~
        transitions:
            complete:
                from: [active]
                to: completed
            abort:
                from: [active]
                to: aborted
        callbacks:
            guard:
                has_przelewy24_subscription_all_intervals_completed_when_completing:
                    on: 'complete'
                    do: ['@bitbag_sylius_przelewy24_plugin.state_guard.has_przelewy24_subscription_all_intervals_completed', 'isEligible']
                    args: ['object']
                has_przelewy24_subscription_at_least_one_aborted_interval_when_aborting:
                    on: 'abort'
                    do: ['@bitbag_sylius_przelewy24_plugin.state_guard.has_przelewy24_subscription_at_least_one_aborted_interval', 'isEligible']
                    args: ['object']
