winzou_state_machine:
    przelewy24_subscription_schedule_interval:
        class: "%bitbag_sylius_przelewy24_plugin.model.przelewy24_subscription_schedule_interval.class%"
        property_path: state
        graph: bitbag_sylius_przelewy24_plugin_przelewy24_subscription_schedule_interval_graph
        state_machine_class: "%sylius.state_machine.class%"
        states:
            scheduled: ~
            unpaid: ~
            fulfilled: ~
            completed: ~
            aborted: ~
        transitions:
            schedule:
                from: [unpaid, aborted]
                to: scheduled
            await_payment:
                from: [scheduled, unpaid]
                to: unpaid
            activate:
                from: [unpaid]
                to: fulfilled
            complete:
                from: [fulfilled]
                to: completed
            abort:
                from: [scheduled, unpaid, fulfilled]
                to: aborted
        callbacks:
            guard:
                is_przelewy24_subscription_schedule_interval_not_paid_when_awaiting_payment:
                    on: ['await_payment']
                    do: ['@bitbag_sylius_przelewy24_plugin.state_guard.is_przelewy24_subscription_schedule_interval_not_paid', 'isEligible']
                    args: ['object']
                is_przelewy24_subscription_schedule_interval_paid_when_activating:
                    on: ['activate']
                    do: ['@bitbag_sylius_przelewy24_plugin.state_guard.is_przelewy24_subscription_schedule_interval_paid', 'isEligible']
                    args: ['object']
                is_przelewy24_subscription_schedule_interval_paid_and_expired_when_completing:
                    on: ['complete']
                    do: ['@bitbag_sylius_przelewy24_plugin.state_guard.is_przelewy24_subscription_schedule_interval_paid_and_expired', 'isEligible']
                    args: ['object']
                has_przelewy24_subscription_schedule_interval_three_failed_attempts_when_aborting:
                    on: ['abort']
                    do: ['@bitbag_sylius_przelewy24_plugin.state_guard.has_przelewy24_subscription_schedule_interval_three_failed_attempts', 'isEligible']
                    args: ['object']
            after:
                resolve_przelewy24_subscription_state:
                    on: ['abort', 'complete']
                    do: ['@bitbag_sylius_przelewy24_plugin.state_resolver.przelewy24_subscription', 'resolve']
                    args: ['object.getSchedule().getSubscription()']
                reset_przelewy24_subscription_schedule_interval_fails_count:
                    on: ['abort']
                    do: ['@bitbag_sylius_przelewy24_plugin.counter.przelewy24_subscription_schedule_interval_failure_counter', 'resetFailsCount']
                    args: ['object']
